# Generated by Django 6.0.2 on 2026-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
